### ISSUE TITLE
Native modules and Windows

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#10]
Just use Linux? A workaround via installing similar yet different NPM packages will lead to using outdated, hard to find packages in the long run. If Linux is not possible, then I suppose it would be necessary

**Comment by HiFaraz** [comment]
Closing per #8: 

Switching to Linux may be the best solution overall but it is overkill for one specific problem if you aren't on Linux. There is a switching cost.

And an alternate solution with the Windows build tools is already provided.

That being said, I'd welcome a PR adding OS-specific options (e.g.a table of pure JS alternatives).

I do agree with your concern about alternate packages. The best recommendation I can give for now is to make sure the package is well supported.
