### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#11]
For hosting I would add in alternatives of Digital Ocean and Amazon web services. `(alt: DO, AWS)`. You have some alternatives for VCS so I think it makes sense here.

**Comment by HiFaraz** [comment]
I've added alternative recommendations sparingly and I'd rather go towards only one solution.

I added BitBucket for the free private repos. I now think that when a developer progresses to the point of needing a private repo they can find BitBucket themselves. Going to remove the double recommendation there.

Thanks for contributing. Please create a new issue if you have a recommended solution that gets a newbie started faster than the current one.

**Comment by JarLowrey** [comment]
> when a developer progresses to the point of needing a private repo they can find BitBucket themselves

Agreed
