### ISSUE TITLE
Cross Platform Framework

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#12]
Electron vs Cordova. I had never heard of Electron, after googling it seems like Cordova focuses mainly on mobile and Electron does desktop. I would remove `Cross platform framework` header, as I think it's confusing. Instead move Electron recommendation under `Developing desktop applications`.

**Comment by HiFaraz** [comment]
Good idea for simplifying the playbook. I'm going to create a parallel structure to the web development section and have put all the tech recommendations under a "Technology stack" section.

Thanks!
