### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by peteyycz** [HiFaraz/node-playbook#17]
I have a few friends who would be interested in this but they are not English speakers, are you planning on supporting multiple languages?

**Comment by HiFaraz** [comment]
I'd love to make this more accessible. Do you mean basically translating the document?

**Comment by peteyycz** [comment]
yes, something like that 😄

**Comment by HiFaraz** [comment]
That sounds great! There may be some issues with keeping all the versions in sync but we might as well start something. Would you like to volunteer?

**Comment by peteyycz** [comment]
I could do the Hungarian version :) if we come up with some tools and such I think we could get some people involved for other languages.

**Comment by HiFaraz** [comment]
Let's just dive right in! 

I added you to https://github.com/HiFaraz/node-playbook-hu

Can you get a couple more people to help you out? 

Let me know when a basic version is up, and I'll link to it from the English one.

**Comment by HiFaraz** [comment]
I also welcome contributors for other languages.

**Comment by peteyycz** [comment]
Woah so quick I'll try to walk my friends through it and do the translation with them on the way! :) thanks a lot

**Comment by HiFaraz** [comment]
You're welcome. Please try to ensure that the recommendations and structure follow this repo. Cheers!

**Comment by HiFaraz** [comment]
Hey @peteyy, are you still planning to work on this? Please let me know within 2 weeks from now.

**Comment by peteyycz** [comment]
Sorry as much as I'd like to I'll have to say no, because I currently have no time for marking the courses. Keep up the good work with the original repository and maybe one day I'll reopen this issue and start hacking. Thanks for providing a great learning resource for others though! 🚀🚀

**Comment by HiFaraz** [comment]
Thanks, I'll close the other repo for now then. Keep in touch.
