### ISSUE TITLE
Publish to GitHub Pages

### ISSUE THREAD

**Issue by hassankhan** [HiFaraz/node-playbook#18]

**Comment by HiFaraz** [comment]
Thanks for your feedback. Can you tell me why this is needed? Maintaining GitHub pages adds extra work.

**Comment by hassankhan** [comment]
I guess it's personal preference, I think it'd be easier to read than a wall of text in the README

**Comment by HiFaraz** [comment]
Thanks for the feedback. I do want this to be easy to read. Would something like gitbooks be a good idea?

**Comment by hassankhan** [comment]
Gitbooks would be even better 😄

**Comment by HiFaraz** [comment]
I'm going to defer this discussion for the future. Thanks for the ideas. The current priority is to finish the upcoming sections.
