### ISSUE TITLE
Terminal-plus package for Atom is inactive.

### ISSUE THREAD

**Issue by talkahe** [HiFaraz/node-playbook#23]
Terminal -plus package for Atom is not currently maintained. There is an issue with this package and newer Atom versions and Windows 10 (jeremyramin/terminal-plus#15). Guys from PlataformIO have forked and updated terminal-plus to work well (+ info jeremyramin/terminal-plus#223).

**Comment by HiFaraz** [comment]
Good catch! Can you please submit a PR to fix this?

**Comment by talkahe** [comment]
Ok, I'll do it

**Comment by HiFaraz** [comment]
Thanks!
