### ISSUE TITLE
How about CloudFlare for the free CDN option?

### ISSUE THREAD

**Issue by lroot** [HiFaraz/node-playbook#26]
https://www.cloudflare.com/features-cdn/
https://www.cloudflare.com/dns/
https://www.cloudflare.com/plans/

They support custom domains and offer CDN and caching services all within their free tier.

**Comment by HiFaraz** [comment]
Interesting, didn't know that you could use a custom domain with a free account.

How is the user experience for a beginner? Super easy or frustrating?

**Comment by lroot** [comment]
In my opinion, CloudFlare's DNS tools are very easy to work with. You do have to have a basic understanding of DNS though. During the setup process, CloudFlare will try and read existing DNS entries and import them which does help with ease-of-setup. 

Another bonus/unique feature is it's ["CNAME Flattening" feature](https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root) which allows you to use a CNAME in the zone apex/root record. So you can CNAME "mywebsite.com" to any host. I've only seen AWS Route 53 support this feature and that's only with its own AWS resources. 

Here's what their DNS management page looks like:

![cloudflare dns](https://cloud.githubusercontent.com/assets/675638/18151734/31992490-6fa6-11e6-93e8-f0b72d2a74f1.png)

**Comment by FlorianWendelborn** [comment]
I'm using them too for every domain I own. Can 100% recommend this, especially for beginners. It even does SSL for you, if you want to. I prefer to use letsencrypt for that though.

**Comment by HiFaraz** [comment]
Closed by #32
