### ISSUE TITLE
Windows & node-gyp

### ISSUE THREAD

**Issue by mateoKaradza** [HiFaraz/node-playbook#3]
I just wanted to leave a comment on this. 
It is true that installing node-gyp on a windows machine gives errors, but there is a solution. 

With Windows 10 Anniversary update, users can enable Ubuntu's bash. Using that, you can install the package without any issue, and I'd recommend it to all people who use windows for developing.

**Comment by FlorianWendelborn** [comment]
I'd recommend people who use Windows for developing (without needing it for technical reasons) to switch TBH.

**Comment by Calinou** [comment]
What about installing the [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)? Does this work for node-gyp?

**Comment by HiFaraz** [comment]
Hi all, thanks for commenting.

@mateoKaradza Ubuntu bash looks very promising, but still not stable.

@dodekeract Switching to Linux may be the best overall strategy but there is a switching cost and will raise new challenges. Therefore it goes against the goal of getting started fast. I'd welcome a PR on "good" alternative modules however. Please see #10.

@Calinou this should already be covered under the "alternative solution". Please let me know if it isn't.
