### ISSUE TITLE
Thoughts about referring to awesome-atom?

### ISSUE THREAD

**Issue by FlorianWendelborn** [HiFaraz/node-playbook#31]
I suggest to at least include a reference to [mehcode/awesome-atom](https://github.com/mehcode/awesome-atom) in [this section](https://github.com/HiFaraz/node-playbook#solution-1).

Thoughts in general about adding a "read more" link to some/all sections?

**Comment by HiFaraz** [comment]
I've been considering something similar as well - an advanced track that takes you beyond "getting started". I like the idea of a link in each section to a document with parallel structure. I.e. clicking the link in the Packages section takes you to the Packages section of Advanced.md

Wanna take this on? I welcome a PR on this.

**Comment by FlorianWendelborn** [comment]
Unfortunately I no longer have a lot of time for random open source projects, I could probably do something in a few days though, if nobody else PRs this.

**Comment by HiFaraz** [comment]
Closing because adding an Advanced version is not a priority until the [upcoming sections](https://github.com/HiFaraz/node-playbook#upcoming-sections) are complete.
