### ISSUE TITLE
Stop calling AWS Lambda "Serverless"

### ISSUE THREAD

**Issue by aem** [HiFaraz/node-playbook#33]
I'm not quite sure what exactly to call it, but I think this would be a good place to start discouraging the use of the term "serverless." Serverless implies that your application somehow works without a server which makes no sense. AWS Lambda is still backed by running servers, as evidenced by the outage a few weeks ago where everyone running a "serverless" environment was affected.

Serverless isn't not using servers, it's using someone else's instead of building your own. There's value in that, but we should come up with a better term (Server as a Service?) to better describe the nature of the feature.

I know this isn't necessarily an issue that's specific to this repository, but if that section is aimed at teaching beginners about web infrastructure we should start by teaching people accurate terminology.

**Comment by HiFaraz** [comment]
I hear you, the techie in me jumped to thinking "there's always a server!". [Functions as a service ](http://martinfowler.com/articles/serverless.html)is much more precise.

Check out #28 though. It's all about preference vs. convention. Node Playbook is just a drop in the ocean - imagine people learning an alternate term here, then going out into the real world and being confused by the term serverless. In that case the playbook has failed to teach people the node ecosystem **as it is**.

I don't think the playbook is the place to redefine stuff - we don't have that kind of influence yet, especially when there are multiple vendors involved. For that reason, I believe we should keep the term serverless.  But yes we should acknowledge that serverless doesn't mean "without a server" - it just means serverless development, not serverless apps.

You made me think of this though: there needs to be a section that explains IaaS vs PaaS vs BaaS vs FaaS/serverless.

**Comment by aem** [comment]
Ah neat. I had never heard BaaS/FaaS before, but that seems like a good way to describe it.

That is a fair point about teaching the ecosystem as it exists today. I'm someone who's impatient and wants the change to happen overnight but I obviously know that won't happen :)

It might still be worth explicitly acknowledging that Serverless is a bad name though.

**Comment by HiFaraz** [comment]
Sounds like we agree :+1:

> I'm someone who's impatient and wants the change to happen overnight but I obviously know that won't happen :)

Right on. Saying no, especially to yourself, is a valuable skill :)

**Comment by HiFaraz** [comment]
> I had never heard BaaS/FaaS before

This is **exactly** what the playbook is good for: discovery. Coming across all of these things is a matter of time and luck. The playbook should aim to eliminate both.
