### ISSUE TITLE
Ready to Provide a solution to Publishing to NPM

### ISSUE THREAD

**Issue by hardog** [HiFaraz/node-playbook#35]
@HiFaraz is there other aspect should pay attention to except [criteria for accepting a solution.](https://github.com/HiFaraz/node-playbook#how-solutions-were-chosen), step by step guide to publish to npm is my idea!

**Comment by HiFaraz** [comment]
Nope, although I recommend you post a summary here first for discussion.

Thank you !

**Comment by hardog** [comment]
@HiFaraz 
- check the module whether published by others
- register npmjs account
- create a dir and npm init
- execute npm publish cmd
- check your module whether published

above is the gist, when push the PR, it would be more detail!

**Comment by HiFaraz** [comment]
Sounds good, couple of points:
- npm init is already covered in the basic workflow, don't need to address this again
- you can't publish without changing the version number, so the workflow should mention upping the version (either patch, minor, or major - add a link to the version numbering section)

**Comment by HiFaraz** [comment]
Closed by #36 a while back
