### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#5]
Add GitLab as VCS. Link all 3 to the sites. GitLab is cheapest w/ a lot of cool features (KanBan boards). GitHub is most well known, BitBucket has Atlassian integration, and is also cheaper than GitHub.
https://github.com/pricing
https://about.gitlab.com/pricing/
https://bitbucket.org/product/pricing

Add code to auto-install atom plugins eg `apm install minimap # https://atom.io/packages/minimap`. Add atom packages `minimap`, `minimap-cursorline`, `linter`, `emmet`, `pigments`, `double-tag`, IDK what else (if you so desire).  

Is source tree really necessary? IDK as I've never used it before. But the source says only for Windows & Mac. I'd think you'd want to encourage devs to use a Linux OS, and learn Git.

Again, I think "Native modules and Windows" section's default solution should be to use Linux haha. A workaround via installing similar yet different NPM packages will lead to using outdated packages in the long run. 

For hosting I would add in alternatives of Digital Ocean and Amazon web services. `(alt: DO, AWS)`. You have some alternatives for VCS so I think it makes sense here. 

Electron vs Cordova. I had never heard of Electron, after googling it seems like Cordova focuses mainly on mobile and Electron does desktop. I would remove `Cross platform framework` header, as I think it's confusing. Instead move Electron recommendation under `Developing desktop applications`. 

[Hybrid framework reference (mobile section)](https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/hybrid-frameworks.md). I've used plain Cordova in a past project, I'll check out what Iconic and PhoneGap contribute.

**Comment by HiFaraz** [comment]
Thanks for the feedback! Can you please create a separate issue for each topic? That way I can  respond and manage them individually.

**Comment by JarLowrey** [comment]
Good point!
