### ISSUE TITLE
Mobile Applications

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#6]
I think the recommendation should be Ionic, not PhoneGap (proprietary) or vanilla Cordova (lacks some performance, no UI helper, Ionic has better API). I've personally used vanilla cordova, but Ionic is also open source and appears to be more recommended.

http://blog.ionic.io/what-is-cordova-phonegap/
https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/hybrid-frameworks.md

Crosswalk should also be included by default to new projects.

https://crosswalk-project.org/
http://blog.ionic.io/crosswalk-comes-to-ionic/

**Comment by JarLowrey** [comment]
[Hybrid framework reference (mobile section)](https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/hybrid-frameworks.md).

**Comment by HiFaraz** [comment]
Check #1 . We're considering react native. The advantage is that we are already recommending react for front end, so this will be less learning for the user. Still keeping this open until we come to a final decision.

**Comment by aem** [comment]
As @HiFaraz touched on, with React recommended as the front-end framework, we should be consistent and use React as the mobile framework as well. Learn once, write anywhere.

**Comment by HiFaraz** [comment]
Closing due to lack of recent activity. We can reopen this if there is interest. Thanks all for your help!
