### ISSUE TITLE
Atom package recommendations

### ISSUE THREAD

**Issue by JarLowrey** [HiFaraz/node-playbook#9]
Add code to auto-install atom plugins eg `apm install minimap # https://atom.io/packages/minimap`. Add atom packages `minimap`, `minimap-cursorline`, `linter`, `emmet`, `pigments`, `double-tag`, IDK what else (if you so desire).

**Comment by HiFaraz** [comment]
Hi,

What is the setup and learning curve like for those plugins?

**Comment by JarLowrey** [comment]
Theyre mostly UI improvements requiring no learning.

[Linter](https://atom.io/packages/linter) does require some modification, [though](https://github.com/steelbrain/linter/wiki/Linter-API)

Minimap shows an overview https://atom.io/packages/minimap

Emmet expands abbreviations and thus probably isn't 100% essential for most people https://atom.io/packages/emmet

Pigments shows colors https://atom.io/packages/pigments

Double-Tag auto edits closing tags when editing HTML https://atom.io/packages/double-tag

There's some others that I was thinking of. I'll find them all later.

**Comment by HiFaraz** [comment]
Thanks for the PR!

Do we need to give some guidance on how to modify the linter? And do how does the user make it run? Will it run on save?

**Comment by JarLowrey** [comment]
Hmmm you know I'm not 100% on how to do that myself. Let me report back to you.

> The HTML, CSS and JavaScript versions work instantly

[blog](https://www.sitepoint.com/10-essential-atom-add-ons/)

**Comment by JarLowrey** [comment]
BTW that terminal-plus package is AMAZING! So glad I clicked your Reddit link!

**Comment by HiFaraz** [comment]
You're welcome! I hated switching back and forth! Tool/solution discovery is a HUGE problem in the ecosystem. Sometimes you're not even aware you have a problem until you see the solution, so how would you find it yourself?

**Comment by HiFaraz** [comment]
I'm closing this because I think we have enough plug-ins for now. There are still outstanding issues and they will get their own GitHub Issue.

Thanks
